"""initial pilot schema

Revision ID: b25b5b74d07e
Revises:
Create Date: 2026-09-19 03:33:53.777272

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b25b5b74d07e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("vehicle_description", sa.String(length=200), nullable=True),
        sa.Column("operator_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "request_limits",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("window", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", "window"),
    )
    op.create_table(
        "idempotency_requests",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("body_hash", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "operation", "key"),
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stations_owner_id"), "stations", ["owner_id"], unique=False)
    op.create_table(
        "connectors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("station_id", sa.UUID(), nullable=False),
        sa.Column("public_code", sa.String(length=50), nullable=False),
        sa.Column("connector_type", sa.String(length=50), nullable=False),
        sa.Column("power_kw", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("price_per_kwh", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("max_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("control_version", sa.Integer(), nullable=False),
        sa.CheckConstraint("power_kw > 0 AND price_per_kwh >= 0 AND max_duration_minutes > 0"),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_code"),
    )
    op.create_index(op.f("ix_connectors_station_id"), "connectors", ["station_id"], unique=False)
    op.create_table(
        "coupons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.Column("station_id", sa.UUID(), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("discount_percent", sa.Integer(), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("discount_percent BETWEEN 0 AND 100"),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connector_id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("firmware_version", sa.String(length=50), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("boot_id", sa.String(length=100), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("physical_state", sa.String(length=20), nullable=False),
        sa.Column("connected", sa.Boolean(), nullable=False),
        sa.Column("reconciled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connectors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index(op.f("ix_devices_connector_id"), "devices", ["connector_id"], unique=False)
    op.create_index(
        "one_active_device", "devices", ["connector_id"], unique=True, postgresql_where=sa.text("NOT revoked")
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("connector_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmation_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connectors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reservations_connector_id"), "reservations", ["connector_id"], unique=False)
    op.create_index(op.f("ix_reservations_user_id"), "reservations", ["user_id"], unique=False)
    op.create_index(
        "one_reservation_connector_id",
        "reservations",
        ["connector_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending_device','confirmed','cancelling')"),
    )
    op.create_index(
        "one_reservation_user_id",
        "reservations",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending_device','confirmed','cancelling')"),
    )
    op.create_table(
        "charging_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("connector_id", sa.UUID(), nullable=False),
        sa.Column("reservation_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("max_cost", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("price_per_kwh", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("discount_percent", sa.Integer(), nullable=False),
        sa.Column("energy_wh", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("soc_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("last_measurement_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cost_estimate", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("end_reason", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "energy_wh >= 0 AND (soc_percent IS NULL OR soc_percent BETWEEN 0 AND 100) AND discount_percent BETWEEN 0 AND 100"
        ),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connectors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_charging_sessions_connector_id"), "charging_sessions", ["connector_id"], unique=False
    )
    op.create_index(op.f("ix_charging_sessions_user_id"), "charging_sessions", ["user_id"], unique=False)
    op.create_index(
        "one_session_connector_id",
        "charging_sessions",
        ["connector_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('starting','charging','stopping')"),
    )
    op.create_index(
        "one_session_user_id",
        "charging_sessions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('starting','charging','stopping')"),
    )
    op.create_table(
        "device_boots",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("boot_id", sa.String(length=100), nullable=False),
        sa.Column("last_sequence", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("device_id", "boot_id"),
    )
    op.create_table(
        "device_commands",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("reservation_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["charging_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "version"),
    )
    op.create_index(op.f("ix_device_commands_device_id"), "device_commands", ["device_id"], unique=False)
    op.create_table(
        "telemetry_samples",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("boot_id", sa.String(length=100), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["charging_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "boot_id", "sequence"),
    )
    # Runtime role is granted only to the API login by the deployment administrator.
    op.execute(
        "DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'chargegrid_api') THEN CREATE ROLE chargegrid_api NOLOGIN; END IF; END $$"
    )
    op.execute("GRANT USAGE ON SCHEMA public TO chargegrid_api")
    op.execute("REVOKE ALL ON TABLE profiles FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE profiles TO chargegrid_api")
    op.execute("ALTER TABLE profiles ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY api_only ON profiles FOR ALL TO chargegrid_api USING (true) WITH CHECK (true)")
    op.execute("REVOKE ALL ON TABLE stations FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE stations TO chargegrid_api")
    op.execute("ALTER TABLE stations ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY api_only ON stations FOR ALL TO chargegrid_api USING (true) WITH CHECK (true)")
    op.execute("REVOKE ALL ON TABLE connectors FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE connectors TO chargegrid_api")
    op.execute("ALTER TABLE connectors ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY api_only ON connectors FOR ALL TO chargegrid_api USING (true) WITH CHECK (true)"
    )
    op.execute("REVOKE ALL ON TABLE devices FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE devices TO chargegrid_api")
    op.execute("ALTER TABLE devices ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY api_only ON devices FOR ALL TO chargegrid_api USING (true) WITH CHECK (true)")
    op.execute("REVOKE ALL ON TABLE reservations FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE reservations TO chargegrid_api")
    op.execute("ALTER TABLE reservations ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY api_only ON reservations FOR ALL TO chargegrid_api USING (true) WITH CHECK (true)"
    )
    op.execute("REVOKE ALL ON TABLE charging_sessions FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE charging_sessions TO chargegrid_api")
    op.execute("ALTER TABLE charging_sessions ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY api_only ON charging_sessions FOR ALL TO chargegrid_api USING (true) WITH CHECK (true)"
    )
    op.execute("REVOKE ALL ON TABLE device_commands FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE device_commands TO chargegrid_api")
    op.execute("ALTER TABLE device_commands ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY api_only ON device_commands FOR ALL TO chargegrid_api USING (true) WITH CHECK (true)"
    )
    op.execute("REVOKE ALL ON TABLE telemetry_samples FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE telemetry_samples TO chargegrid_api")
    op.execute("ALTER TABLE telemetry_samples ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY api_only ON telemetry_samples FOR ALL TO chargegrid_api USING (true) WITH CHECK (true)"
    )
    op.execute("REVOKE ALL ON TABLE coupons FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE coupons TO chargegrid_api")
    op.execute("ALTER TABLE coupons ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY api_only ON coupons FOR ALL TO chargegrid_api USING (true) WITH CHECK (true)")
    op.execute("REVOKE ALL ON TABLE idempotency_requests FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE idempotency_requests TO chargegrid_api")
    op.execute("ALTER TABLE idempotency_requests ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY api_only ON idempotency_requests FOR ALL TO chargegrid_api USING (true) WITH CHECK (true)"
    )
    op.execute("REVOKE ALL ON TABLE request_limits FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE request_limits TO chargegrid_api")
    op.execute("ALTER TABLE request_limits ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY api_only ON request_limits FOR ALL TO chargegrid_api USING (true) WITH CHECK (true)"
    )
    op.execute("REVOKE ALL ON TABLE device_boots FROM PUBLIC")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE device_boots TO chargegrid_api")
    op.execute("ALTER TABLE device_boots ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY api_only ON device_boots FOR ALL TO chargegrid_api USING (true) WITH CHECK (true)"
    )
    op.execute(
        """DO $$ DECLARE table_name text; BEGIN
        FOREACH table_name IN ARRAY string_to_array('profiles,stations,connectors,devices,reservations,charging_sessions,device_commands,telemetry_samples,coupons,idempotency_requests,request_limits,device_boots', ',') LOOP
          IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'anon') THEN
            EXECUTE format('REVOKE ALL ON TABLE %I FROM anon', table_name);
          END IF;
          IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'authenticated') THEN
            EXECUTE format('REVOKE ALL ON TABLE %I FROM authenticated', table_name);
          END IF;
        END LOOP; END $$"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telemetry_samples")
    op.drop_index(op.f("ix_device_commands_device_id"), table_name="device_commands")
    op.drop_table("device_commands")
    op.drop_table("device_boots")
    op.drop_index(
        "one_session_user_id",
        table_name="charging_sessions",
        postgresql_where=sa.text("status IN ('starting','charging','stopping')"),
    )
    op.drop_index(
        "one_session_connector_id",
        table_name="charging_sessions",
        postgresql_where=sa.text("status IN ('starting','charging','stopping')"),
    )
    op.drop_index(op.f("ix_charging_sessions_user_id"), table_name="charging_sessions")
    op.drop_index(op.f("ix_charging_sessions_connector_id"), table_name="charging_sessions")
    op.drop_table("charging_sessions")
    op.drop_index(
        "one_reservation_user_id",
        table_name="reservations",
        postgresql_where=sa.text("status IN ('pending_device','confirmed','cancelling')"),
    )
    op.drop_index(
        "one_reservation_connector_id",
        table_name="reservations",
        postgresql_where=sa.text("status IN ('pending_device','confirmed','cancelling')"),
    )
    op.drop_index(op.f("ix_reservations_user_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_connector_id"), table_name="reservations")
    op.drop_table("reservations")
    op.drop_index("one_active_device", table_name="devices", postgresql_where=sa.text("NOT revoked"))
    op.drop_index(op.f("ix_devices_connector_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_table("coupons")
    op.drop_index(op.f("ix_connectors_station_id"), table_name="connectors")
    op.drop_table("connectors")
    op.drop_index(op.f("ix_stations_owner_id"), table_name="stations")
    op.drop_table("stations")
    op.drop_table("idempotency_requests")
    op.drop_table("request_limits")
    op.drop_table("profiles")
    # ### end Alembic commands ###
