"""Regenerate the Android icon, splash and LVGL mark from the login emblem.

Run on macOS with Pillow available in the active Python environment. The SVG
uses the same Material EV_STATION glyph and red color as the login screen.
"""

import shutil
import subprocess
from hashlib import sha256
from pathlib import Path

from PIL import Image


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    assets = root / "apps/mobile/assets"
    source = assets / "brand_mark.svg"
    icon = assets / "icon.png"
    subprocess.run(["sips", "-s", "format", "png", str(source), "--out", str(icon)], check=True)
    shutil.copyfile(icon, assets / "splash_android.png")

    mark = Image.open(icon).convert("RGB").resize((64, 64), Image.Resampling.LANCZOS)
    pixels = []
    for red, green, blue in mark.get_flattened_data():
        rgb565 = ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)
        pixels.append(f"CG_RGB565(0x{rgb565 >> 8:02X}, 0x{rgb565 & 0xFF:02X})")
    lines = ["    " + ", ".join(pixels[i : i + 8]) + "," for i in range(0, len(pixels), 8)]
    digest = sha256(icon.read_bytes()).hexdigest()
    output = f'''/*
 * Generated by tools/generate_brand_assets.py from apps/mobile/assets/brand_mark.svg.
 * apps/mobile/assets/icon.png SHA-256: {digest}
 * RGB565 byte order follows LVGL 8's LV_COLOR_16_SWAP setting.
 */

#include "chargegrid_logo.h"

#ifdef CHARGEGRID_PANEL_ENABLED
#include <stdint.h>

#if LV_COLOR_16_SWAP
#define CG_RGB565(high, low) high, low
#else
#define CG_RGB565(high, low) low, high
#endif

static const uint8_t chargegrid_logo_map[] = {{
{chr(10).join(lines)}
}};

const lv_img_dsc_t chargegrid_logo_64x64 = {{
    .header.always_zero = 0,
    .header.w = 64,
    .header.h = 64,
    .header.cf = LV_IMG_CF_TRUE_COLOR,
    .data_size = sizeof(chargegrid_logo_map),
    .data = chargegrid_logo_map,
}};

#undef CG_RGB565
#endif  // CHARGEGRID_PANEL_ENABLED
'''
    (root / "firmware/esp32/src/chargegrid_logo.c").write_text(output)


if __name__ == "__main__":
    main()
